# Generated by Django 2.0.4 on 2018-09-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20180915_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-c_time'], 'verbose_name': 'todos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'users'},
        ),
    ]
