# Generated by Django 2.0.4 on 2018-09-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20180915_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-c_time'], 'verbose_name': 'todo'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
    ]
