# Generated by Django 2.0.4 on 2018-09-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20180915_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'top'), (2, 'important'), (3, 'common')], default=3),
        ),
    ]
